name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  pre-commit-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  create-pubsub-topic:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        run: echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > gcloud-service-key.json
      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - name: Remove service key
        run: rm gcloud-service-key.json
      - name: Set Google Cloud project
        run: gcloud config set project cicdtest-421422
      - name: Create Pub/Sub topic
        run: |
          if ! gcloud pubsub topics list --filter="name:weather-topic" | grep weather-topic; then
            gcloud pubsub topics create weather-topic
          fi

  deploy-cloud-function:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        run: echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > gcloud-service-key.json
      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - name: Remove service key
        run: rm gcloud-service-key.json
      - name: Set Google Cloud project
        run: gcloud config set project cicdtest-421422
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy generate_weather_summary \
            --runtime=python310 \
            --entry-point=generate_weather_summary \
            --region=europe-west1 \
            --source=. \
            --trigger-topic weather-topic \
            --memory=512MB \
            --set-env-vars "API_KEY=${{ secrets.API_KEY }},SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}"

  create-scheduler-job:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Google Cloud SDK
        run: echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > gcloud-service-key.json
      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file gcloud-service-key.json
      - name: Remove service key
        run: rm gcloud-service-key.json
      - name: Set Google Cloud project
        run: gcloud config set project cicdtest-421422
      - name: Create Scheduler Job
        run: |
          if ! gcloud scheduler jobs describe weather-summary-job --location=europe-west1 &> /dev/null; then
            gcloud scheduler jobs create pubsub weather-summary-job \
              --schedule="0 20 * * *" \
              --time-zone="CET" \
              --topic=weather-topic \
              --message-body="{}" \
              --location=europe-west1
          fi
